extends Node

var ruta: String = "res://src"

#aSalidaPorPantalla
var AsalidaPorPantalla: Node = load(ruta + "/aSalidaPorPantalla/AsalidaPorPantalla.tscn").instantiate()
#bVariables
var Avariables: Node = load(ruta + "/bVariables/Avariables.tscn").instantiate()
#cConstantes
var Aconstantes: Node = load(ruta + "/cConstantes/Aconstantes.tscn").instantiate()
#dConcatenacion
var Aconcatenacion: Node = load(ruta + "/dConcatenacion/Aconcatenacion.tscn").instantiate()
#eOperadores
var AoperadoresAritmeticos: Node = load(ruta + "/eOperadores/AoperadoresAritmeticos.tscn").instantiate()
var BoperadoresIncremento: Node = load(ruta + "/eOperadores/BoperadoresIncremento.tscn").instantiate()
var CoperadoresDecremento: Node = load(ruta + "/eOperadores/CoperadoresDecremento.tscn").instantiate()
#fTiposDeDatos
var AtiposDeDatos: Node = load(ruta + "/fTiposDeDatos/AtiposDeDatos.tscn").instantiate()
#gConversionDeTiposDeDatos
var AintAfloat: Node = load(ruta + "/gConversionDeTiposDeDatos/AintAfloat.tscn").instantiate()
var BintAstring: Node = load(ruta + "/gConversionDeTiposDeDatos/BintAstring.tscn").instantiate()
var CfloatAint: Node= load(ruta + "/gConversionDeTiposDeDatos/CfloatAint.tscn").instantiate()
var DfloatAstr: Node = load(ruta + "/gConversionDeTiposDeDatos/DfloatAstr.tscn").instantiate()
var EstrAint: Node = load(ruta + "/gConversionDeTiposDeDatos/EstrAint.tscn").instantiate()
var FstrAfloat: Node = load(ruta + "/gConversionDeTiposDeDatos/FstrAfloat.tscn").instantiate()
var GmostrarTipoDeDato: Node = load(ruta + "/gConversionDeTiposDeDatos/GmostrarTipoDeDato.tscn").instantiate()
#hEstructurasDeControl
var AcondicionalIF: Node = load(ruta + "/hEstructurasDeControl/AcondicionalIF.tscn").instantiate()
var BcondicionalELIF: Node = load(ruta + "/hEstructurasDeControl/BcondicionalELIF.tscn").instantiate()
var CoperadoresLogicos: Node = load(ruta + "/hEstructurasDeControl/CoperadoresLogicos.tscn").instantiate()
var DbucleWhile: Node = load(ruta + "/hEstructurasDeControl/DbucleWhile.tscn").instantiate()
var EbucleFor: Node = load(ruta + "/hEstructurasDeControl/EbucleFor.tscn").instantiate()
var Fbreak: Node = load(ruta + "/hEstructurasDeControl/Fbreak.tscn").instantiate()
#iLecturaDeDatos
var AlecturaPorConsola: Node = load(ruta + "/iLecturaDeDatos/AlecturaPorConsola.tscn").instantiate()
#jFunciones
var Afunciones: Node = load(ruta + "/jFunciones/Afunciones.tscn").instantiate()
var BfuncionesConParametrosObligatorios: Node = load(ruta + "/jFunciones/BfuncionesConParametrosObligatorios.tscn").instantiate()
var CfuncionesConParametrosOpcionales: Node = load(ruta + "/jFunciones/CfuncionesConParametrosOpcionales.tscn").instantiate()
var DfuncionesConRetorno: Node = load(ruta + "/jFunciones/DfuncionesConRetorno.tscn").instantiate()
var EejecutarFuncionDentroDeOtra: Node = load(ruta + "/jFunciones/EejecutarFuncionDentroDeOtra.tscn").instantiate()
var FfuncionesLambda: Node = load(ruta + "/jFunciones/FfuncionesLambda.tscn").instantiate()
var GvariablesGlobalesYLocales: Node = load(ruta + "/jFunciones/GvariablesGlobalesYLocales.tscn").instantiate()
var HfuncionePredefinidas: Node = load(ruta + "/jFunciones/HfuncionePredefinidas.tscn").instantiate()
#kArrays
var AcrearArray: Node = load(ruta + "/kArrays/AcrearArray.tscn").instantiate()
var BindicesEnArrays: Node = load(ruta + "/kArrays/BindicesEnArrays.tscn").instantiate()
var CcambiarValorDeUnIndice: Node = load(ruta + "/kArrays/CcambiarValorDeUnIndice.tscn").instantiate()
var DagregarUnElementoAUnArray: Node = load(ruta + "/kArrays/DagregarUnElementoAUnArray.tscn").instantiate()
var ErecorrerArray: Node = load(ruta + "/kArrays/ErecorrerArray.tscn").instantiate()
var FarrayMultidimensional: Node = load(ruta + "/kArrays/FarrayMultidimensional.tscn").instantiate()
var GfuncionesPredefinidasParaArrays: Node = load(ruta + "/kArrays/GfuncionesPredefinidasParaArrays.tscn").instantiate()
#lDiccionarios
var AcrearDiccionario: Node = load(ruta + "/lDiccionarios/AcrearDiccionario.tscn").instantiate()
var BclavesEnDiccionarios: Node = load(ruta + "/lDiccionarios/BclavesEnDiccionarios.tscn").instantiate()
var CdiccionariosDentroDeArrays: Node = load(ruta + "/lDiccionarios/CdiccionariosDentroDeArrays.tscn").instantiate()
#mSistemaDeArchivos
var AabrirArchivo: Node = load(ruta + "/mSistemaDeArchivos/AabrirArchivo.tscn").instantiate()
var BescribirEnArchivo: Node = load(ruta + "/mSistemaDeArchivos/BescribirEnArchivo.tscn").instantiate()
var CleerUnArchivoConGetAsText: Node = load(ruta + "/mSistemaDeArchivos/CleerUnArchivoConGetAsText.tscn").instantiate()
var DleerUnArchivoConGetLine: Node = load(ruta + "/mSistemaDeArchivos/DleerUnArchivoConGetLine.tscn").instantiate()
var EcopiarUnArchivo: Node = load(ruta + "/mSistemaDeArchivos/EcopiarUnArchivo.tscn").instantiate()
var FmoverUnArchivo: Node = load(ruta + "/mSistemaDeArchivos/FmoverUnArchivo.tscn").instantiate()
var GeliminarUnArchivo: Node = load(ruta + "/mSistemaDeArchivos/GeliminarUnArchivo.tscn").instantiate()
var HcomprobarSiExisteUnArchivo: Node = load(ruta + "/mSistemaDeArchivos/HcomprobarSiExisteUnArchivo.tscn").instantiate()
var IcrearCarpeta: Node = load(ruta + "/mSistemaDeArchivos/IcrearCarpeta.tscn").instantiate()
var JeliminarCarpeta: Node = load(ruta + "/mSistemaDeArchivos/JeliminarCarpeta.tscn").instantiate()
var KcopiarCarpeta: Node = load(ruta + "/mSistemaDeArchivos/KcopiarCarpeta.tscn").instantiate()
var LlistarContenidoDeUnaCarpeta: Node = load(ruta + "/mSistemaDeArchivos/LlistarContenidoDeUnaCarpeta.tscn").instantiate()
#nManejoDeErrores
var AcapturarExcepcion: Node = load(ruta + "/nManejoDeErrores/AcapturarExcepcion.tscn").instantiate()
#oPOO
var AclasesAtributosMetodosObjetos_Main: Node = load(ruta + "/oPOO/AclasesAtributosMetodosObjetos/Main.tscn").instantiate()
var Bconstructor_Main: Node = load(ruta + "/oPOO/Bconstructor/Main.tscn").instantiate()
var CdetectarTipoDeInstancia_Main: Node = load(ruta + "/oPOO/CdetectarTipoDeInstancia/Main.tscn").instantiate()
var DvisibilidadDeAtributos_Main: Node = load(ruta + "/oPOO/DvisibilidadDeAtributos/Main.tscn").instantiate()
var Eherencia_Main: Node = load(ruta + "/oPOO/Eherencia/Main.tscn").instantiate()

func _ready():
	pass
	#AsalidaPorPantalla.codigo()
	#Avariables.codigo()
	#Aconstantes.codigo()
	#Aconcatenacion.codigo()
	#AoperadoresAritmeticos.codigo()
	#BoperadoresIncremento.codigo()
	#CoperadoresDecremento.codigo()
	#AtiposDeDatos.codigo()
	#AintAfloat.codigo()
	#BintAstring.codigo()
	#CfloatAint.codigo()
	#DfloatAstr.codigo()
	#EstrAint.codigo()
	#FstrAfloat.codigo()
	#GmostrarTipoDeDato.codigo()
	#AcondicionalIF.codigo()
	#BcondicionalELIF.codigo()
	#CoperadoresLogicos.codigo()
	#DbucleWhile.codigo()
	#EbucleFor.codigo()
	#Fbreak.codigo()
	#AlecturaPorConsola.codigo() #TODO.
	#Afunciones.codigo()
	#BfuncionesConParametrosObligatorios.codigo()
	#CfuncionesConParametrosOpcionales.codigo()
	#DfuncionesConRetorno.codigo()
	#EejecutarFuncionDentroDeOtra.codigo()
	#FfuncionesLambda.codigo()
	#GvariablesGlobalesYLocales.codigo()
	#HfuncionePredefinidas.codigo()
	#AcrearArray.codigo()
	#BindicesEnArrays.codigo()
	#CcambiarValorDeUnIndice.codigo()
	#DagregarUnElementoAUnArray.codigo()
	#ErecorrerArray.codigo()
	#FarrayMultidimensional.codigo()
	#GfuncionesPredefinidasParaArrays.codigo()
	#AcrearDiccionario.codigo()
	#BclavesEnDiccionarios.codigo()
	#CdiccionariosDentroDeArrays.codigo()
	#AabrirArchivo.codigo()
	#BescribirEnArchivo.codigo() #TODO.
	#CleerUnArchivoConGetAsText.codigo()
	#DleerUnArchivoConGetLine.codigo()
	#EcopiarUnArchivo.codigo()
	#FmoverUnArchivo.codigo()
	#GeliminarUnArchivo.codigo()
	#HcomprobarSiExisteUnArchivo.codigo()
	#IcrearCarpeta.codigo()
	#JeliminarCarpeta.codigo()
	#KcopiarCarpeta.codigo() #TODO.
	#LlistarContenidoDeUnaCarpeta.codigo()
	#AcapturarExcepcion.codigo()
	#AclasesAtributosMetodosObjetos_Main.codigo()
	#Bconstructor_Main.codigo()
	#CdetectarTipoDeInstancia_Main.codigo()
	#DvisibilidadDeAtributos_Main.codigo()
	Eherencia_Main.codigo()
